--
-- Simple
--
CREATE TABLE IF NOT EXISTS simple (
    id             BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    firstname      TEXT                         NOT NULL
);

CREATE INDEX IF NOT EXISTS simple_firstname_idx ON simple USING btree (firstname);

--
-- END
--
